libname lavdat 'E:\WORK\DATASET';
data aa;
set lavdat.loan_credit_clean;
run;

proc contents data=aa;
run;

%let varnums=
AmountDelinquent_num
AvailableBankcardCredit_num
BankcardUtilization_num
BorrowerAPR_num
BorrowerRate_num
ClosedDate_num
CreditScoreRangeLower_num
CreditScoreRangeUpper_num
CurrentCreditLines_num
CurrentDelinquencies_num
DateCreditPulled_num
DebtToIncomeRatio_num
DelinquenciesLast7Years_num
EmploymentStatusDuration_num
EstimatedEffectiveYield_num
EstimatedLoss_num
EstimatedReturn_num
FirstRecordedCreditLine_num
InquiriesLast6Months_num
InvestmentFromFriendsAmount_num
InvestmentFromFriendsCount_num
Investors_num
LP_CollectionFees_num
LP_CustomerPayments_num
LP_CustomerPrincipalPayments_num
LP_GrossPrincipalLoss_num
LP_InterestandFees_num
LP_NetPrincipalLoss_num
LP_NonPrincipalRecoverypay_num
LP_ServiceFees_num
LenderYield_num
ListingCategory__numeric
ListingCreationDate_num
ListingNumber_num
LoanCurrentDaysDelinquent_num
LoanFirstDefaultedCycleNum_num
LoanMonthsSinceOrigination_num
LoanNumber_num
LoanOriginalAmount_num
LoanOriginationDate_num
MonthlyLoanPayment_num
OnTimeProsperPayments_num
OpenCreditLines_num
OpenRevolvingAccounts_num
OpenRevolvingMonthlyPayment_num
PercentFunded_num
ProsperPayments1Mon_PlusLate_num
ProsperPayments_LT_OneMonth_num
ProsperPrincipalBorrowed_num
ProsperPrincipalOutstanding_num
ProsperRating__numeric
ProsperScore_num
PublicRecordsLast10Years_num
PublicRecordsLast12Months_num
Recommendations_num
RevolvingCreditBalance_num
ScorexChangeAtTimeOfListing_num
StatedMonthlyIncome_num
Term_num
TotalCreditLinespast7years_num
TotalInquiries_num
TotalProsperLoans_num
TotalProsperPaymentsBilled_num
TotalTrades_num
TradesNeverDelinquentpercent_num
TradesOpenedLast6Months_num;
%let varchars=
BorrowerState
ClosedDate_clean
CreditGrade
CurrentlyInGroup
DateCreditPulled_clean
EmploymentStatus
FirstRecordedCreditLine_clean
GroupKey
IncomeRange
IncomeVerifiable
IsBorrowerHomeowner
ListingCreationDate_clean
ListingKey
LoanKey
LoanOriginationDate_clean
LoanOriginationQuarter
LoanStatus
MemberKey
Occupation
ProsperRating__Alpha_;

proc means data=aa n nmiss mean min max;
   var &varnums;
run;
